[project]
name = "bes-velocimetry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["h5py", "matplotlib", "nvtx"]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"


[project.scripts]
bes-velocimetry = "bes_velocimetry:main_para"
bes-hello = "bes_velocimetry:main"

[tool.ruff]
exclude = []
line-length = 120
indent-width = 4
target-version = "py310"
